export const RABBITMQ_CONSTANTS = {
  QUEUES: {
    RECORD_SYNC: 'record.sync.queue',
    NOTIFICATION_BATCH: 'notification.batch.queue',
  },
  PATTERNS: {
    RECORD_SYNC: 'record.sync',
    NOTIFICATION_SEND_BATCH: 'notification.send.batch',
  },
  CLIENTS: {
    RECORD_SYNC_PRODUCER: 'RECORD_SYNC_PRODUCER',
    NOTIFICATION_BATCH_PRODUCER: 'NOTIFICATION_BATCH_PRODUCER',
  },
} as const;

export const RMQ_CLIENT_MAP = {
  [RABBITMQ_CONSTANTS.CLIENTS.RECORD_SYNC_PRODUCER]:
    RABBITMQ_CONSTANTS.QUEUES.RECORD_SYNC,

  [RABBITMQ_CONSTANTS.CLIENTS.NOTIFICATION_BATCH_PRODUCER]:
    RABBITMQ_CONSTANTS.QUEUES.NOTIFICATION_BATCH,
} as const;
