export const ErrorCodes = {
  // 400 - Client Errors
  INVALID_TAG_ID: 'INVALID_TAG_ID',
  INVALID_TAG_NAME: 'INVALID_TAG_NAME',

  //403 - Forbidden
  NOT_ALLOWED_DELETE_TAG: 'NOT_ALLOWED_TAG_',

  // 404 - Not Found
  TAG_NOT_FOUND: 'TAG_NOT_FOUND',

  // 409 - Conflict
  TAG_ALREADY_EXISTS: 'TAG_ALREADY_EXISTS',
  SYSTEM_TAG_NOT_DELETABLE: 'SYSTEM_TAG_NOT_DELETABLE',
};
