export enum ConnectionErrorCode {
  INVALID_CONNECTION = 'INVALID_CONNECTION',
  RECORD_ACCESS_DENIED = 'RECORD_ACCESS_DENIED',
  RECORD_NOT_FOUND = 'RECORD_NOT_FOUND',
  CONNECTION_ALREADY_EXISTS = 'CONNECTION_ALREADY_EXISTS',
}
