export enum ConnectionErrorCode {
  INVALID_CONNECTION = 'INVALID_CONNECTION',
  CONNECTION_ALREADY_EXISTS = 'CONNECTION_ALREADY_EXISTS',
  PAIR_CONNECTION_NOT_FOUND = 'PAIR_CONNECTION_NOT_FOUND',
  CONNECTION_NOT_FOUND = 'CONNECTION_NOT_FOUND',
}
