export const RecordErrorCode = {
  // 400 - Client Errors
  RECORD_ACCESS_DENIED: 'RECORD_ACCESS_DENIED',
  RECORD_NOT_FOUND: 'RECORD_NOT_FOUND',
  TITLE_MISSING: 'TITLE_MISSING',
  TITLE_TOO_LONG: 'TITLE_TOO_LONG',
  CONTENT_TOO_LONG: 'CONTENT_TOO_LONG',
  LOCATION_MISSING: 'LOCATION_MISSING',
  INVALID_LATITUDE: 'INVALID_LATITUDE',
  INVALID_LONGITUDE: 'INVALID_LONGITUDE',
  LOCATION_NAME_MISSING: 'LOCATION_NAME_MISSING',
  LOCATION_ADDRESS_MISSING: 'LOCATION_ADDRESS_MISSING',
  TOO_MANY_IMAGES: 'TOO_MANY_IMAGES',
  IMAGE_SIZE_EXCEEDED: 'IMAGE_SIZE_EXCEEDED',
  INVALID_IMAGE_FORMAT: 'INVALID_IMAGE_FORMAT',
  INVALID_JSON_FORMAT: 'INVALID_JSON_FORMAT',

  // 500 - Server Errors
  IMAGE_PROCESSING_FAILED: 'IMAGE_PROCESSING_FAILED',
  RECORD_CREATION_FAILED: 'RECORD_CREATION_FAILED',
  RECORD_DELETION_FAILED: 'RECORD_DELETION_FAILED',
  IMAGE_DELETION_FAILED: 'IMAGE_DELETION_FAILED',
} as const;
