export const MapsErrorCode = {
  ADDRESS_NOT_FOUND: 'ADDRESS_NOT_FOUND',
  ADDRESS_MISSING: 'ADDRESS_MISSING',
  INVALID_LATITUDE: 'INVALID_LATITUDE',
  INVALID_LONGITUDE: 'INVALID_LONGITUDE',
} as const;
