export const AuthErrorCode = {
  EMAIL_ALREADY_EXISTS: 'AUTH_EMAIL_ALREADY_EXISTS',
  EMAIL_ALREADY_SENT: 'AUTH_EMAIL_ALREADY_SENT',
  EMAIL_VERIFICATION_EXPIRED: 'AUTH_EMAIL_VERIFICATION_EXPIRED',
  EMAIL_VERIFICATION_FAILED: 'AUTH_EMAIL_VERIFICATION_FAILED',
  EMAIL_VERIFICATION_TOO_MANY_TRIES: 'AUTH_EMAIL_VERIFICATION_TOO_MANY_TRIES',

  INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  SOCIAL_ACCOUNT_LOGIN: 'AUTH_SOCIAL_ACCOUNT_LOGIN',

  INVALID_ACCESS_TOKEN: 'INVALID_ACCESS_TOKEN',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
} as const;
